### ISSUE TITLE
Kaomoji 是如何打出来的？

### ISSUE THREAD

**Issue by roachsinai** [alswl/Rime#1]
感谢提供的词库想问一下，下图这个`不行`是如何显示的，输入拼音之后需要按什么键？我如果按下`|`就成了`不行|`。

![Kaomoji Snapshot](https://raw.githubusercontent.com/alswl/Rime/master/snapshots/kaomoji.png)

**Comment by alswl** [comment]
你试试 nihao 可以正常出现 Hi~ o(*￣▽￣*)ブ 么？
你使用的输入方案是全拼双拼或者其他？

数据都在 `luna_pinyin.kaomoji.dict.yaml` 里面，通过 `luna_pinyin.custom.dict.yaml` 中的 `luna_pinyin.kaomoji` 引入。

**Comment by roachsinai** [comment]
emm，都可以了，我看了一下`luna_pinyin.kaomoji` 里面原来是`不行了`，我看图片把字母`l`看成了管道符号`|`。

感谢回复。

**Comment by crimx** [comment]
请问小鹤双拼下如何输入 emoji 和 kaomoji ？我已经重命名了 `luna_pinyin.custom.dict.yaml`，但是直接打没有出现？

**Comment by crimx** [comment]
知道什么原因了，修改 `double_pinyin_flypy.schema.yaml`

```diff
translator:
-  dictionary: luna_pinyin
+  dictionary: luna_pinyin.custom
```

其中一些冲突不知道如何解决？

- `luna_pinyin.emoji.scomper` 会导致单个字母 `c` 时没有出现候选词。
- `luna_pinyin.kaomoji` 会导致单个字母 `l` 时没有出现候选词。
