### ISSUE TITLE
(;´༎ຶД༎ຶ`) 	ku si中间有两个空格

### ISSUE THREAD

**Issue by roachsinai** [alswl/Rime#3]
(;´༎ຶД༎ຶ`) 	ku si，有两个空格，linux上使用electron-wechat输出kaomoji之后后面会加上`&nbsp;`也就是一个空格。

https://github.com/alswl/Rime/blob/80d497dd7ef20a90a41154cd0ef05e48256e6e68/luna_pinyin.kaomoji.dict.yaml#L169

但是，将上面多余的空格删除之后，重新部署之后不能生效。打印出来后面仍然有一个空格。

**Comment by roachsinai** [comment]
emm，需要先从userdb中删除那个表情。希望能够更新一下，好像只有这个(;´༎ຶД༎ຶ`)后面多一个空格。

**Comment by alswl** [comment]
Thanks for your issue, fixed.

Space was confused by non-breaking space, very very .... minor difference.

Detected this space difference by diffing unicode
(;´༎ຶД༎ຶ`)

```
~ $ cat /tmp/a.txt | xxd
00000000: c2a0 0a                                  ...
~ $ c /tmp/space.txt | xxd
00000000: 200a                                      .
```

via [Non-breaking space - Wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space)
