### ISSUE TITLE
大神能不能帮忙转化几个搜狗的词库？

### ISSUE THREAD

**Issue by Vergegung** [alswl/Rime#4]
医学类的词库可以帮忙转一下吗？macos环境下不太会用那个深蓝转化软件，谢谢

**Comment by alswl** [comment]
我提供了一个小脚本可以在 Mac 命令行里面快速转换。
https://github.com/alswl/ascel

具体使用可以参考 https://github.com/alswl/Rime/blob/master/luna_pinyin.wangluoliuxingxinci.dict.yaml
头部注释信息。

如果还是遇到问题，也可以提出来。
