### ISSUE TITLE
求安装说明

### ISSUE THREAD

**Issue by sinoon** [alswl/Rime#5]
请问下，MacOS 上如何安装？plum 那个不是很懂...求大佬给一个指点...

**Comment by alswl** [comment]
@sinoon Rime 的安装可以使用 brew，plum 的安装见文档 [rime/plum: 東風破 /plum/: Rime configuration manager and input schema repository](https://github.com/rime/plum)

总安装流程

```
# 安装 mac 的 Rime（Squirrel）
brew cask install squirrel

# 进入配置目录，如果没有则创建
cd $HOME/Library/Rime

# clone plum 东风破
git clone --depth 1 https://github.com/rime/plum.git

# 安装官方的几个输入方案
./plum/rime-install essay
./plum/rime-install pinyin-simp
./plum/rime-install luna-pinyin
./plum/rime-install double-pinyin
./plum/rime-install combo-pinyin
./plum/rime-install wubi
```

**Comment by sinoon** [comment]
太赞了！非常感谢！我走了类似的步骤，失败过很多次，所以就放弃了...

**Comment by twlz0ne** [comment]
> 总安装流程
> 
> ```
> # 安装 mac 的 Rime（Squirrel）
> brew cask install squirrel
> 
> # 进入配置目录，如果没有则创建
> cd $HOME/Library/Rime
> 
> # clone plum 东风破
> git clone --depth 1 https://github.com/rime/plum.git
> 
> # 安装官方的几个输入方案
> ./plum/rime-install essay
> ./plum/rime-install pinyin-simp
> ./plum/rime-install luna-pinyin
> ./plum/rime-install double-pinyin
> ./plum/rime-install combo-pinyin
> ./plum/rime-install wubi
> ```

还是没看明白，本仓库应该如何使用，以上步骤似乎没有体现？

**Comment by alswl** [comment]
你在哪一步遇到问题了呢？

twlz0ne ***@***.***>于2021年9月8日 周三15:57写道：

**Comment by twlz0ne** [comment]
刚刚安装 Rime，对于配置还没有头绪。才明白是要用这个仓库直接代替 `~/Library/Rime`。
